---
- name: Install wireguard
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items:
    - wireguard-dkms
    - wireguard-tools
  tags:
    - wireguard_install
    - wireguard_upgrade

