---
- ansible.builtin.include_tasks: "{{ ansible_distribution | lower }}_repositories.yml"
  tags:
    - wireguard_install

- ansible.builtin.include_tasks: "{{ ansible_distribution | lower }}_linux_headers.yml"
  tags:
    - wireguard_install

- name: Install wireguard-dkms
  apt:
    name: "{{ 'wireguard-dkms=' + wireguard_dkms_version if wireguard_version != '' else 'wireguard-dkms' }}"
    state: present
    update_cache: yes
  register: upgrade
  tags:
    - wireguard_install
    - wireguard_upgrade

- name: Install wireguard
  apt:
    name: "{{ 'wireguard=' + wireguard_version if wireguard_version != '' else 'wireguard' }}"
    state: present
    update_cache: yes
  register: upgrade
  tags:
    - wireguard_install
    - wireguard_upgrade

