---
- name: Enable wireguard COPR repository
  ansible.builtin.get_url:
    dest: /etc/yum.repos.d/_copr_jdoss-wireguard.repo
    url: "https://copr.fedorainfracloud.org/coprs/jdoss/wireguard/repo/{{ (ansible_distribution == 'Fedora') | ternary('fedora', 'epel') }}-{{ ansible_distribution_major_version }}/jdoss-wireguard-{{ (ansible_distribution == 'Fedora') | ternary('fedora', 'epel') }}-{{ ansible_distribution_major_version }}.repo"
  when: ansible_distribution_major_version is version('9', '<')
  tags:
    - wireguard_install

- name: Enable EPEL
  ansible.builtin.package:
    name: epel-release
    state: present
  when: ansible_distribution != "Fedora"
  tags:
    - wireguard_install

- name: Install wireguard-dkms on Fedora, RedHat, CentOS
  ansible.builtin.package:
    name: "{{ 'wireguard-dkms-' + wireguard_dkms_version if wireguard_dkms_version != '' else 'wireguard-dkms' }}"
    state: present
  register: upgrade
  when: ansible_distribution_major_version is version('9', '<')
  tags:
    - wireguard_install
    - wireguard_upgrade

- name: Install wireguard-tools on Fedora, RedHat, CentOS
  ansible.builtin.package:
    name: "{{ 'wireguard-tools-' + wireguard_tools_version if wireguard_tools_version != '' else 'wireguard-tools' }}"
    state: present
  tags:
    - wireguard_install
    - wireguard_upgrade

